- front-end/src/App.js
> right lean image

- front-end/src/App.js
> another test

- front-end/src/App.js
- front-end/src/Login/Login.js
Hi - added a Login component. Still needs some help with centering. For now <Login /> is included within the App.js if you want to look at it. If you think we need to postpone pulling just let me know and I'll try to work more when I have a moment.
> added Login component

- front-end/src/TipUpdate/TipUpdate.js
> prelim tip update code

- front-end/src/TipUpdate/TipUpdate.js
> tip input cont.

- front-end/src/App.js
- front-end/src/Login/Login.js
corrected issues from previous pull request.
> fixed issues

- front-end/src/TipUpdate/TipUpdate.js
> da good stuff

- front-end/package-lock.json
- front-end/package.json
- front-end/src/App.js
remove merge conflicted code in app.js
> remove merge conflicted code

- front-end-appsync-build/src/App.js
figured out how to grab username, swapped that out for email.  far more useful.
> pulls current username for use in TipEntry table

- front-end/src/Components/ProcessTips/ProcessTips.js
- front-end/src/Components/ViewTipInfo/ViewTipInfo.css
- front-end/src/Components/ViewTipInfo/ViewTipInfo.js
Will complete the rest of this data processing as soon as possible. Didn't add this component to app.js,
so, you can merge the pull request without any worries
> average hourly tips by business name

- front-end/amplify/#current-cloud-backend/amplify-meta.json
- front-end/amplify/#current-cloud-backend/api/pooledhouse/build/cloudformation-template.json
- front-end/amplify/#current-cloud-backend/api/pooledhouse/build/parameters.json
- front-end/amplify/#current-cloud-backend/api/pooledhouse/build/schema.graphql
- front-end/amplify/#current-cloud-backend/api/pooledhouse/schema.graphql
- front-end/amplify/backend/amplify-meta.json
- front-end/amplify/backend/api/pooledhouse/build/cloudformation-template.json
- front-end/amplify/backend/api/pooledhouse/build/parameters.json
- front-end/amplify/backend/api/pooledhouse/build/schema.graphql
- front-end/amplify/backend/api/pooledhouse/schema.graphql
- front-end/amplify/backend/awscloudformation/nested-cloudformation-stack.yml
- front-end/src/App.js
- front-end/src/Components/Map/map.js
- front-end/src/Components/TipInfoForm/TipInfoForm.js
- front-end/src/graphql/mutations.js
- front-end/src/graphql/queries.js
- front-end/src/graphql/schema.json
- front-end/src/graphql/subscriptions.js
Edited GraphQL schema to include neighborhood column for ease of integration with NYC Chloropleth.  Added neighborhood input to TipInfoForm.
> edited schema, added neighborhood column to TipInfoForm, added map functionality.

- front-end/src/App.js
- front-end/src/Components/Map/map.js
- front-end/src/Components/TipInfoForm/TipInfoForm.js
Fixed bug where neighborhood was not being submitted from tip input form correctly, adjusted chloropleth labels to show rounded values.
> fixed neighborhood selection bug

- front-end/src/Components/Map/map.js
- front-end/src/Components/Map/mapFunctions.js
> Map tile dynamic coloring, moved new map functions to mapFunctions.js, added map filtering by day of week

- front-end/src/Components/Map/map.js
- front-end/src/Components/Map/mapFunctions.js
Added dropdown selection filters to map view, allows instantaneous filtering by day, shift, and position.  Also included reset filter button.  Functionality uses state.
> map filtering working for day, shift time, position

- front-end/src/App.js
- front-end/src/Components/Map/map.js
- front-end/src/Components/ViewTipInfo/PositionOption.js
- front-end/src/Components/ViewTipInfo/ViewTipInfoList.js
map.js -> moved the reset filter button so it's centered and doesn't look too shitty.
app.js, ViewTipInfoList -> refactored the relevant list view components into one component that is called on App.js, ViewTipInfoList.  This will ease app.js state issues and make navigation easier to manage in the future.
> Small changes to Map View (moved a button) and List View (refactored into one component)

- front-end/src/App.css
- front-end/src/App.js
- front-end/src/Components/Map/map.js
- front-end/src/Components/Map/mapFunctions.js
-Centered the map on the map view page, using variable height based on browser window,
-Removed the annoying navbar at the top of the page, added a signout button.
-changed some export syntax in mapFunctions.js for Shofi testing
> Centered Map, Removed amazon auth bar at top of page, added signout button

- db_function_test_app/test-app/src/App.js
- front-end/src/App.js
- front-end/src/Components/ViewTipInfo/ViewTipInfoList.js
fixed conditional views--rewired app.js with some new state variables to handle different pages.  Should be working a-ok.
> fixed conditional views, not buggy anymore

- front-end/amplify/#current-cloud-backend/amplify-meta.json
- front-end/amplify/#current-cloud-backend/hosting/S3AndCloudFront/parameters.json
- front-end/amplify/backend/amplify-meta.json
- front-end/amplify/backend/awscloudformation/nested-cloudformation-stack.yml
- front-end/amplify/backend/hosting/S3AndCloudFront/parameters.json
- front-end/src/App.js
- front-end/src/Components/Map/mapFunctions.js
- front-end/src/Components/Search/Search.js
- front-end/src/Components/Search/searchFunctions.js
- front-end/src/aws-exports.js
> added search functionality, added username to mytips button, removed some deprecated state variables

- front-end/src/Components/Search/Search.js
See title.  Same filters as for map.
> added search filters

- front-end/src/App.js
- front-end/src/Components/TipInfoForm/TipInfoForm.css
Fixed bug where search page was showing up when 'user's tips' button was clicked.
> search view bugfix

- front-end/public/index.html
- front-end/src/App.css
- front-end/src/Components/Map/map.js
- front-end/src/Components/Map/mapFunctions.js
- front-end/src/Components/ReactNYC/ReactNYC.js
Added function to convert address to latlong using Google Maps API.  Have not implemented on tip entry yet, however.  Still working on that.
Also, removed the footer.
> Added code for converting address to latlong, removed footer.

- front-end/src/Components/TipInfoForm/TipInfoForm.js
> fixed no consecutive tip entries bug

- front-end/src/Components/ProcessTips/ProcessTips.js
- front-end/src/Components/ViewTipInfo/ViewBarChart.js
- front-end/src/Components/ViewTipInfo/ViewCompany.js
- front-end/src/Components/ViewTipInfo/ViewReportedTips.js
- front-end/src/Components/ViewTipInfo/ViewTipInfoList.js
> Update for process.js, viewReportedTips, viewBarChart and documentation
